apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-micronaut-http
  name: ms-micronaut-http
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-micronaut-http
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-micronaut-http
    spec:
      containers:
        - image: gcr.io/artful-chiller-259423/github.com/agrawald/ms-micronaut-http
          imagePullPolicy: IfNotPresent
          name: ms-micronaut-http-sha256-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: ms-micronaut-http
  name: ms-micronaut-http-hpa-qhcr
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-micronaut-http
---
apiVersion: v1
kind: Service
metadata:
  name: ms-micronaut-http-service
  namespace: default
  labels:
    app: ms-micronaut-http
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ms-micronaut-http
  type: LoadBalancer
